<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Foreigner_password-container</name>
   <tag></tag>
   <elementGuidId>97686102-563c-42ae-9c6f-a3f108366ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.password-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Foreigner'])[1]/following::div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5503b31e-665e-448a-abe0-a73544d87c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password-container</value>
      <webElementGuid>69cba5b9-a25d-4a6e-ac84-3556cd79840d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[@class=&quot;undefined&quot;]/app-register-layout[1]/div[@class=&quot;content content-footer&quot;]/app-profile-registration[1]/div[@class=&quot;form-container&quot;]/div[@class=&quot;form-body&quot;]/div[@class=&quot;regis-form&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;password-container&quot;]</value>
      <webElementGuid>e90c2139-6c05-4f65-a8fd-b4c920abff12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foreigner'])[1]/following::div[6]</value>
      <webElementGuid>29568ed9-e514-4fd4-947e-0dd4df54ce3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สมัครสมาชิก SET Member'])[1]/following::div[6]</value>
      <webElementGuid>65bdc560-925a-4773-9a17-3b58f203d43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Strong'])[1]/preceding::div[2]</value>
      <webElementGuid>a42cc9ae-4e91-4b7a-b570-e56624de3720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รหัสผ่านต้องเป็น Strong เท่านั้นถึงจะผ่าน ตัวอย่างรหัสผ่านที่ถูกต้อง : Jelly22fish'])[1]/preceding::div[4]</value>
      <webElementGuid>65b61b58-1f16-4e50-867c-5df35c3d4f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div</value>
      <webElementGuid>aa417c46-a72e-47e3-8149-e2bd390c41e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
