<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_reCAPTCHA_recaptcha-checkbox-border</name>
   <tag></tag>
   <elementGuidId>ab10e508-9c87-4252-8624-ad14dd234b21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.recaptcha-checkbox-border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='recaptcha-anchor']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>06593167-e7c1-4764-b999-f3d54d55f993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recaptcha-checkbox-border</value>
      <webElementGuid>1aa96e3e-5b01-489a-8eec-7079378358b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>132df4dc-1ff2-4fe0-9020-5fdc612ca774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-anchor&quot;)/div[@class=&quot;recaptcha-checkbox-border&quot;]</value>
      <webElementGuid>63596f82-569a-431e-8ec0-1329c711c0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_- thairath.co.th/iframe__a-vrcpy2iw1fb5</value>
      <webElementGuid>71947997-1040-43ae-b26f-06bd13df532a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='recaptcha-anchor']/div</value>
      <webElementGuid>f3bdc289-6964-4fbf-9e8d-026c36e304dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>f339a76a-045f-40ee-a222-7e34bf95e32f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
