<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__a-vrcpy2iw1fb5</name>
   <tag></tag>
   <elementGuidId>037191c3-3704-4946-9001-4aad9ce961e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-vrcpy2iw1fb5&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-vrcpy2iw1fb5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e2ff693a-0ef8-4b7b-8df3-f62b60c60806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>3b50dda7-a490-4165-bdf0-755272677f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcUe1wUAAAAAFMGSVkkXS1v7BgIZHDhfOA8mkIw&amp;co=aHR0cHM6Ly93d3cudGhhaXJhdGguY28udGg6NDQz&amp;hl=en&amp;type=image&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=um86znxp2dw1</value>
      <webElementGuid>26374485-ec67-4fc2-952d-beb2f3a671a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>fe6e4f25-3e40-489c-b297-35ba61e74e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>e7eeb213-eee4-4489-9170-303959d2822d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7fd8baf0-fb1d-4468-ae16-dade7a82253e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-vrcpy2iw1fb5</value>
      <webElementGuid>b23d70d4-0855-4367-b30a-616700a932f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c5dce131-5369-4d5e-a725-8c6b1fb69b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>dfdc9c4e-310e-4f33-b78c-120a84df791b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>8b939f6f-100a-4170-8086-e8acd436dcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Register&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;css-1lbny9m e18gpnny0&quot;]/div[@class=&quot;css-fx5ja ee21rrp78&quot;]/form[1]/div[@class=&quot;__Register_Captcha css-qxfrkz ee21rrp84&quot;]/div[1]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>8835bba6-4504-4976-b6e3-1aa13e40a6d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-vrcpy2iw1fb5']</value>
      <webElementGuid>dc6ec89d-dc95-42c4-99f7-beab7517783b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Register']/div/div[3]/div[2]/form/div[4]/div/div/div/div/iframe</value>
      <webElementGuid>2e639ec1-6fd3-4dff-8bab-0c78a888c2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>38b7a27f-4667-47c6-b05e-04d02bfa0f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcUe1wUAAAAAFMGSVkkXS1v7BgIZHDhfOA8mkIw&amp;co=aHR0cHM6Ly93d3cudGhhaXJhdGguY28udGg6NDQz&amp;hl=en&amp;type=image&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=um86znxp2dw1' and @name = 'a-vrcpy2iw1fb5']</value>
      <webElementGuid>30e4900f-b5f2-402f-ba2f-f495676a0414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
