<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__password_match</name>
   <tag></tag>
   <elementGuidId>8bcce6ad-347d-4072-b618-1bf936d5fe87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password_match&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password_match']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70bf2ea5-77b2-487f-ab44-89fb0d02a74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>844d18ca-c799-432f-8c05-daf00de59e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password_match</value>
      <webElementGuid>7a0e77ef-35f9-4c53-8c99-0d2dc2c804d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ยืนยันรหัสผ่าน</value>
      <webElementGuid>01905de3-0faf-4e77-a434-a1e2560854bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Register&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;css-1lbny9m e18gpnny0&quot;]/div[@class=&quot;css-fx5ja ee21rrp78&quot;]/form[1]/div[@class=&quot;__Register_input_pass_confirm css-19cstr2 ee21rrp79&quot;]/input[1]</value>
      <webElementGuid>0b1f53c3-559d-4327-8007-3e13a09ea3b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password_match']</value>
      <webElementGuid>4365a365-8bbc-4c38-a04f-950abe74b0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Register']/div/div[3]/div[2]/form/div[3]/input</value>
      <webElementGuid>9ea8cc08-f217-4fe8-9640-e68db744de37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>39c8bda8-57b7-4bb4-9428-4582c6ed7970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password_match' and @placeholder = 'ยืนยันรหัสผ่าน']</value>
      <webElementGuid>b5c73d2c-4fc6-490e-8638-0341a05c7ccd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
