<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__isPolicy</name>
   <tag></tag>
   <elementGuidId>f7502f3b-475b-4ab5-90d4-08cfc54b92f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='policy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>302bdc13-2ac3-4423-8d7b-4bcc1a3ff9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>735e1e47-5982-40f5-a5b4-7047ac8fc077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isPolicy</value>
      <webElementGuid>3ac9af16-7b8f-42ad-b923-621aae4be8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>policy</value>
      <webElementGuid>b14a2a0c-9bc2-42ab-b1ed-07478f99b519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;policy&quot;)</value>
      <webElementGuid>0558baca-85da-4ce8-8977-20ece5a0d59d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='policy']</value>
      <webElementGuid>f58148a0-87a7-4617-b1a8-475fb8f53a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PolicyBox']/form/div/input</value>
      <webElementGuid>82687ca6-5ddf-485d-b0ed-0b1ec0c2a210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>c89ae454-d03a-4c68-86e2-9831a72a93bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'isPolicy' and @id = 'policy']</value>
      <webElementGuid>7872a737-83d3-4b7e-bbc5-7c30c14a44af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
